name: Google Chat Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Google Chat Message
        run: |
          # cleanup commit msg
          COMMIT_MSG=$(cat << 'EOF' | jq -Rs .
          ${{ github.event.head_commit.message }}
          EOF
          )
          # remove additional spaces
          COMMIT_MSG=${COMMIT_MSG#\"}
          COMMIT_MSG=${COMMIT_MSG%\"}

          curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"text\": \"🚀 *New Update to ${{ github.repository }}*\nLink: health.llazat.in \n\n*Latest:*\n${COMMIT_MSG}\"
          }" \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
